version: "2.1"

networks:
  test:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_debug
    ports:
      - "18080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Djava.security.egd=file:/dev/./urandom -jar /project/target/currency-1.0.0-SNAPSHOT.jar

  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - test
