# db configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cod
  # mail configuration
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: yourgamil@gmail.com
    password: youremailpassword
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
# custom property to control application consistency
jasypt:
  mandatory: true
